services:
  db:
    image: 'postgres:17-alpine'
    container_name: tmdb-bdd
    ports:
      - '${DB_LOCAL_PORT}:${DB_DOCKER_PORT}'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    shm_size: 128mb

  spring-service:
    container_name: tmdb-back
    build:
      context: ~/IdeaProjects/tmdb/backend
      dockerfile: Dockerfile
      cache_from:
        - spring-service:v1.0
    image: spring-service:v1.0
    depends_on:
      - db
    environment:
      - DRIVER_CLASS_NAME=${DRIVER_CLASS_NAME}
      - FRONT_URL=${FRONT_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - TMDB_API_BASE_URL=${TMDB_API_BASE_URL}
      - TMDB_MOST_RATED_MOVIES_API_PATH=${TMDB_MOST_RATED_MOVIES_API_PATH}
      - TMDB_POPULAR_MOVIES_API_PATH=${TMDB_POPULAR_MOVIES_API_PATH}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - LANGUAGE=${LANGUAGE}
      - SORT_BY=${SORT_BY}
      - BEST_MOVIES_TOTAL_PAGES=${BEST_MOVIES_TOTAL_PAGES}
    ports:
      - '${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}'
    networks:
      - backend
      - frontend

  vue-service:
    build:
      context: ~/IdeaProjects/tmdb/frontend
      cache_from:
        - vue-service:v1.0
    image: vue-service:v1.0
    container_name: tmdb-front
    depends_on:
      - spring-service
    ports:
      - '${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}'
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
    postgres_data:
