spring:
  application:
    name: movie-app
  jackson:
    deserialization:
      fail-on-unknown-properties: false
#    serialization:
#      fail-on-empty-beans: false

  config:
    import:
      - classpath:database.yml
      - classpath:movie-api.yml
      - optional:file:./.env[.properties]

frontend:
  url: ${FRONT_URL}