on:
  push:
    branches: ['main', 'feats/add-ci-cd-pipeline']

jobs:
  build-deploy:
    name: Build and Deploy that Spring Boot project
    runs-on: ubuntu-latest
    env:
      POM_FILE: ./backend/pom.xml
    steps:
      - name: Checkout to project code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Unit tests
        run: mvn -B test --file ${{env.POM_FILE}}

      - name: Build the application
        run: |
          cd backend
          mvn clean
          mvn -B package --file pom.xml