on:
  push:
    branches: ['main', 'feats/add-ci-cd-pipeline']

jobs:
  build-deploy:
    name: Build and Deploy that Spring Boot project
    runs-on: ubuntu-latest
    env:
      TARGET_REGISTRY: docker.io
      BACKEND_DIR: ./backend
      BACKEND_DOCKERFILE: ./backend/Dockerfile
      POM_FILE: ./backend/pom.xml
    steps:
      - name: Get current date and time
        id: datetime
        run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H.%M.%S')"

      - name: Set Docker image tag
        run: echo "IMAGE_TAG=v${{ steps.datetime.outputs.date }}" >> $GITHUB_ENV

      - name: Checkout to project code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Unit tests
        run: mvn -B test --file ${{env.POM_FILE}}

      - name: Build the application
        run: |
          cd backend
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BACKEND_DIR }}
          dockerfile: ${{ env.BACKEND_DOCKERFILE }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tmdb-app:${{env.IMAGE_TAG}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BACKEND_DIR }}
          dockerfile: ${{ env.BACKEND_DOCKERFILE }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tmdb-app:${{env.IMAGE_TAG}}
